[theme]
# plain, solarized-(dark|light), slick, modern, bad-wolf, gruvbox-(dark|light), space-villain
name = "solarized-dark"
[theme.overrides]
separator = ""

[icons]
# none, awesome, awesome5, material
name = "awesome"
[icons.overrides]
backlight_full = " \uf042 "
backlight_partial1 = " \uf042 "
backlight_partial2 = " \uf042 "
backlight_partial3 = " \uf042 "
power-off = " \uf011 "
calendar = " \uf133 "

# [[block]]
# block = "nvidia_gpu"
# label = ""
# show_utilization = false
# show_memory = false
# interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 2
format = "{average}°C"
chip = "*-isa-*"

[[block]]
info = 30
block = "cpu"
interval = 2
format = "{utilization}%"
per_core = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false
interval = 2

# [[block]]
# block = "custom"
# on_click = "sh i3-sensible-terminal -e neomutt"
# command = "sh ~/.config/i3/scripts/notmuch.sh"
# json = true
# interval = 300

[[block]]
block = "pacman"
interval = 86400
format = "{pacman}"
format_up_to_date = "0"
format_singular = "{pacman}"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
# hide_when_uptodate = true

# [[block]]
# block = "net"
# format = "{speed_down}"
# interval = 2
# use_bits = false
# hide_inactive = true
# hide_missing = true

[[block]]
block = "music"
buttons = ["play"]
max_width = 21
seek_step = 5000
hide_when_empty = true

[[block]]
block = "sound"
on_click = "pavucontrol"
[block.mappings]
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "backlight"

[[block]]
block = "custom"
on_click = "exec blueman-manager"
command = "sh ~/.config/i3/scripts/bluetoothctl.sh"
json = true
interval = 12

[[block]]
block = "networkmanager"
on_click = "networkmanager_dmenu"
device_format = "{icon} {ap}"
ap_format = "{ssid}"
max_ssid_width = 6

[[block]]
block = "custom"
# on_click = "sh ~/.config/i3/scripts/.sh"
command = "sh ~/.config/i3/scripts/calendar.sh"
json = true
interval = 60

[[block]]
block = "custom"
on_click = "sh ~/.config/i3/scripts/powermenu.sh"
command = "echo '{\"icon\":\"power-off\", \"state\":\"Idle\", \"text\":\"\"}'"
json = true
interval = "once"

# [[block]]
# block = "kdeconnect"
